id: AF423CF51
title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
  Life of the Gentle Protector Guru'
type: translation
pechas:
- I05C7C3A2
- I9D5855EC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:47.389936
  last_modified_at: 2023-01-04 11:38:47.389949
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I05C7C3A2/807C: F32A
  I9D5855EC/3279: F32A
